# Generated by Django 4.2.19 on 2025-02-16 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='personal_id',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9,12}$', 'Personal ID must be 9-12 digits')], verbose_name='Personal ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=30, unique=True, verbose_name='Phone Number'),
        ),
    ]
